name: ESLint Validation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: ESLint Action eslintrc
        uses: mrdivyansh/eslint-action@v1.0.7
